matrix:
  include:
    - language: php
      env: PHPUNIT_VERSION=4.8.*

      php: 5.4

      before_install:
       - travis_retry composer self-update
       - travis_retry composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-interaction --no-update

      install: 
       - travis_retry composer update --prefer-dist --no-interaction

      script: 
       - cd tests
       - ../vendor/bin/phpunit
       
    - language: node_js
      node_js: node
      script: npm run production
